openrouter_manager/__init__.py,sha256=LNFfEfBYuZrAueJLfqfFytdWZitequ23Wo31roMVQTA,589
openrouter_manager/adapter/ai_agent.py,sha256=8XRyMakPZjsaVDqnDaiv3LTtTQ30Zo0yYVv0R3aeI10,2891
openrouter_manager/adapter/llm_exception.py,sha256=9ezVCmN7-FFn4t_EVhh1ne1CXIt_dTRUuYeKRD-DpcM,255
openrouter_manager/adapter/prompt.py,sha256=AhIbDn2y6-xqx4wLx_8zQNpKbrDd6ZbxX4gg5D45fSo,748
openrouter_manager/adapter/variable.py,sha256=hSSDORgIiHnQnf1rUZG4VDnR-oY7esdYnWJRfua2rP4,117
openrouter_manager-0.1.0.dist-info/LICENSE.txt,sha256=YNO1ZtHyD2LDwS8XOgaaRKXWixM-I16c29MuGrCcT48,1079
openrouter_manager-0.1.0.dist-info/METADATA,sha256=PgIwa_437Zbv19XrSnfDp58mPHh4837SPh2fXGlhAiE,3693
openrouter_manager-0.1.0.dist-info/WHEEL,sha256=Kol19cahXavY536r5Aj6aAgK_6CmctrOu3bgNJMSNJA,109
openrouter_manager-0.1.0.dist-info/top_level.txt,sha256=KRRyn1OM887c-6897P77Pwc0IMR4QsLEMuvalub-H5w,19
openrouter_manager-0.1.0.dist-info/RECORD,,
